[package]
name = "price-getter"
version = "0.1.0"
authors = ["Greg Kapka <greg@oraclize.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
